export const TECH_STACK_OPTIONS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C/C++",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Node.js",
  ".NET",
  "Django",
  "Spring Boot",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Machine Learning",
  "Data Engineering",
  "Cybersecurity",
  "DevOps",
  "Linux/Unix",
  "Agile/Scrum",
] as const;

export const EXPERIENCE_LEVELS = [
  { label: "0–2 years", value: 1 },
  { label: "3–5 years", value: 4 },
  { label: "6–10 years", value: 8 },
  { label: "10+ years", value: 12 },
] as const;

export const WORK_PREFERENCES = ["Remote", "Hybrid", "Onsite"] as const;
