import type { Mission, CareerPath, RoadmapCategory } from './types';

export const missions: Mission[] = [
  {
    slug: 'linux-hardening-fundamentals',
    title: 'Linux Hardening Fundamentals',
    description: 'Secure a fresh Ubuntu server from scratch — configure SSH, set up firewalls, manage users, and eliminate attack surface.',
    tools: ['Linux', 'Bash', 'UFW', 'SSH', 'auditd'],
    difficulty: 'Beginner',
    duration: '4–6 hours',
    category: 'System Security',
    overview: `In this mission you'll take a freshly provisioned Ubuntu 22.04 server and harden it against common attack vectors. You'll disable unnecessary services, configure secure SSH access with key-based authentication, set up a stateful firewall with UFW, enforce strong password policies, and enable audit logging. By the end you'll have a repeatable hardening checklist you can apply to any Linux system.`,
    tasks: [
      {
        id: 't1',
        title: 'Initial System Audit',
        description: 'Run a baseline security audit using lynis. Document open ports, running services, and current user accounts.',
      },
      {
        id: 't2',
        title: 'SSH Hardening',
        description: 'Disable root login, enforce key-based authentication only, change the default port, and configure fail2ban to block brute-force attempts.',
      },
      {
        id: 't3',
        title: 'Firewall Configuration',
        description: 'Install and configure UFW. Define an allow-list of required ports (SSH, HTTP, HTTPS) and deny everything else by default.',
      },
      {
        id: 't4',
        title: 'User & Permission Management',
        description: 'Create a non-root admin user, configure sudo access with least privilege, and audit file permissions on sensitive directories.',
      },
      {
        id: 't5',
        title: 'Audit Logging',
        description: 'Configure auditd to track privilege escalation, file access on /etc, and login events. Export logs to a centralised location.',
      },
    ],
    skills: ['Linux administration', 'Firewall configuration', 'SSH security', 'Audit logging', 'Least-privilege principles'],
    jobRelevance: 'Linux hardening is a foundational skill for SOC analysts, cloud security engineers, and DevSecOps engineers. Most cloud workloads run on Linux — knowing how to secure them is non-negotiable.',
  },
  {
    slug: 'docker-security-lab',
    title: 'Docker Security Lab',
    description: 'Scan container images for CVEs, build minimal secure images, and enforce runtime security policies across a multi-container stack.',
    tools: ['Docker', 'Trivy', 'Docker Compose', 'Linux', 'Falco'],
    difficulty: 'Intermediate',
    duration: '6–8 hours',
    category: 'Container Security',
    overview: `Containers are everywhere in modern infrastructure — and misconfigured containers are one of the top attack vectors. In this mission you'll learn to scan images for known vulnerabilities, build hardened Docker images using multi-stage builds and minimal base images, configure container runtime security with resource limits and read-only filesystems, and detect suspicious runtime behaviour with Falco.`,
    tasks: [
      {
        id: 't1',
        title: 'Image Vulnerability Scanning',
        description: 'Use Trivy to scan a set of provided Docker images. Identify critical and high CVEs, document them, and propose remediation strategies.',
      },
      {
        id: 't2',
        title: 'Build a Hardened Image',
        description: 'Rewrite a provided Dockerfile using a distroless base image, multi-stage build, non-root user, and read-only filesystem.',
      },
      {
        id: 't3',
        title: 'Runtime Security Policies',
        description: 'Configure Docker Compose with security options: drop Linux capabilities, set memory/CPU limits, mount filesystems read-only, and disable privilege escalation.',
      },
      {
        id: 't4',
        title: 'Network Segmentation',
        description: 'Define custom Docker networks to isolate containers. Verify that only intended services can communicate with each other.',
      },
      {
        id: 't5',
        title: 'Runtime Threat Detection',
        description: 'Install Falco and write custom rules to detect shell spawning inside containers, unexpected file writes, and privilege escalation attempts.',
      },
    ],
    skills: ['Container security', 'Vulnerability scanning', 'Image hardening', 'Runtime threat detection', 'Network segmentation'],
    jobRelevance: 'Container security expertise is in high demand. Cloud Security Engineers and DevSecOps roles at every major company require hands-on Docker and Kubernetes security skills.',
  },
  {
    slug: 'cloud-security-audit-aws',
    title: 'Cloud Security Audit with AWS',
    description: 'Audit a misconfigured AWS environment — find exposed S3 buckets, overly permissive IAM roles, open security groups, and missing CloudTrail.',
    tools: ['AWS', 'Terraform', 'Python', 'AWS CLI', 'Prowler'],
    difficulty: 'Intermediate',
    duration: '8–10 hours',
    category: 'Cloud Security',
    overview: `Cloud misconfigurations account for the majority of data breaches. In this mission you'll audit a deliberately misconfigured AWS environment using both manual techniques and automated tools like Prowler. You'll identify and remediate: public S3 buckets, wildcard IAM policies, overly permissive VPC security groups, disabled CloudTrail, and unencrypted EBS volumes. Finally, you'll codify the correct configuration using Terraform.`,
    tasks: [
      {
        id: 't1',
        title: 'Automated Audit with Prowler',
        description: 'Run Prowler against the target AWS account. Review the CIS benchmark findings and prioritise critical risks.',
      },
      {
        id: 't2',
        title: 'S3 Bucket Security',
        description: 'Identify publicly accessible S3 buckets. Review bucket policies and ACLs, enable Block Public Access, and implement server-side encryption.',
      },
      {
        id: 't3',
        title: 'IAM Policy Remediation',
        description: 'Identify IAM users/roles with wildcard permissions. Apply least-privilege principles and replace overly broad policies with scoped ones.',
      },
      {
        id: 't4',
        title: 'VPC & Security Group Hardening',
        description: 'Find security groups with 0.0.0.0/0 ingress rules on sensitive ports. Tighten rules and document the required access matrix.',
      },
      {
        id: 't5',
        title: 'Terraform Remediation',
        description: 'Codify all security fixes as Terraform resources. Run terraform plan/apply and verify the changes using the AWS CLI.',
      },
    ],
    skills: ['AWS security', 'IAM policies', 'Cloud compliance (CIS)', 'Terraform', 'Incident response'],
    jobRelevance: 'Cloud Security Engineers and DevSecOps roles require deep AWS knowledge. Cloud misconfiguration skills are tested in interviews and used daily on the job.',
  },
  {
    slug: 'automated-threat-detection-pipeline',
    title: 'Automated Threat Detection Pipeline',
    description: 'Build a SIEM-style detection pipeline using Python and the ELK stack to ingest logs, detect anomalies, and trigger automated alerts.',
    tools: ['Python', 'Elasticsearch', 'Logstash', 'Kibana', 'Suricata', 'Sigma'],
    difficulty: 'Advanced',
    duration: '10–14 hours',
    category: 'Threat Detection',
    overview: `SOC analysts spend most of their time investigating alerts — but the pipeline that generates those alerts is often opaque. In this mission you'll build a full threat detection pipeline from scratch: ingest web server logs and network traffic using Logstash, write detection rules using Sigma, correlate events in Elasticsearch, visualise them in Kibana, and write Python automation to enrich and escalate high-severity events.`,
    tasks: [
      {
        id: 't1',
        title: 'ELK Stack Setup',
        description: 'Deploy Elasticsearch, Logstash, and Kibana using Docker Compose. Configure TLS and authentication between components.',
      },
      {
        id: 't2',
        title: 'Log Ingestion Pipeline',
        description: 'Write Logstash pipelines to ingest Apache/Nginx access logs and Suricata alerts. Parse, normalise, and enrich events with GeoIP data.',
      },
      {
        id: 't3',
        title: 'Sigma Detection Rules',
        description: 'Convert three real-world Sigma rules (brute-force, port scan, data exfiltration) into Elasticsearch queries. Test against sample log data.',
      },
      {
        id: 't4',
        title: 'Kibana Dashboards',
        description: 'Build a SOC dashboard showing: top source IPs, alert severity timeline, geo-map of sources, and anomaly trends.',
      },
      {
        id: 't5',
        title: 'Python Alert Automation',
        description: 'Write a Python script that polls Elasticsearch for new high-severity alerts, enriches them via VirusTotal, and sends formatted notifications via webhook.',
      },
    ],
    skills: ['SIEM operations', 'ELK Stack', 'Sigma rules', 'Python scripting', 'Log analysis', 'Threat detection'],
    jobRelevance: 'SOC Analysts and Security Engineers who can build and tune detection pipelines command premium salaries. SIEM expertise is listed in virtually every senior security role.',
  },
  {
    slug: 'cicd-security-integration',
    title: 'CI/CD Security Integration',
    description: 'Embed security scanning into a GitHub Actions pipeline — SAST, dependency scanning, secret detection, container scanning, and IaC validation.',
    tools: ['GitHub Actions', 'Docker', 'Terraform', 'Semgrep', 'Trivy', 'tfsec', 'Gitleaks'],
    difficulty: 'Advanced',
    duration: '8–12 hours',
    category: 'DevSecOps',
    overview: `Security is most effective when it's automated and shift-left. In this mission you'll take an existing CI/CD pipeline and transform it into a security-first workflow. You'll add static analysis with Semgrep, dependency vulnerability scanning, secret detection with Gitleaks, container image scanning with Trivy, and Infrastructure-as-Code security validation with tfsec — all gated to block insecure deployments.`,
    tasks: [
      {
        id: 't1',
        title: 'Secret Detection',
        description: 'Integrate Gitleaks into the pipeline. Intentionally commit a fake secret, verify it\'s caught, then configure allowlist rules for false positives.',
      },
      {
        id: 't2',
        title: 'Static Application Security Testing',
        description: 'Add Semgrep to scan Python/JavaScript code for injection vulnerabilities, hardcoded credentials, and insecure dependencies.',
      },
      {
        id: 't3',
        title: 'Container Image Scanning',
        description: 'Integrate Trivy to scan the application Docker image on every PR. Configure severity thresholds and block merges on CRITICAL findings.',
      },
      {
        id: 't4',
        title: 'IaC Security Scanning',
        description: 'Add tfsec and Checkov to validate Terraform code. Identify and fix three deliberately insecure Terraform resources.',
      },
      {
        id: 't5',
        title: 'Security Gates & Reporting',
        description: 'Implement a consolidated security report as a PR comment. Configure branch protection rules so all security gates must pass before merge.',
      },
    ],
    skills: ['DevSecOps', 'GitHub Actions', 'SAST', 'Container security', 'IaC security', 'Shift-left security'],
    jobRelevance: 'DevSecOps is the fastest-growing security discipline. Companies that have adopted DevOps need security engineers who can speak the same language as developers and automate security into pipelines.',
  },
];

export const careerPaths: CareerPath[] = [
  {
    id: 'soc-analyst',
    title: 'SOC Analyst',
    icon: '🔍',
    description: 'Monitor, detect, and respond to security threats in real time. The entry point for many cybersecurity careers — high demand, clear progression.',
    avgSalary: '£35,000 – £55,000',
    skills: ['SIEM (Splunk/ELK)', 'Incident response', 'Log analysis', 'Threat intelligence', 'Network monitoring', 'Sigma/YARA rules'],
    missionSlugs: ['linux-hardening-fundamentals', 'automated-threat-detection-pipeline'],
    learningOrder: [
      'Linux fundamentals & command line',
      'Networking basics (TCP/IP, DNS, HTTP)',
      'SIEM concepts and log analysis',
      'Threat detection & Sigma rules',
      'Incident response procedures',
      'Threat intelligence feeds',
    ],
  },
  {
    id: 'cloud-security-engineer',
    title: 'Cloud Security Engineer',
    icon: '☁️',
    description: 'Secure cloud infrastructure across AWS, Azure, or GCP. Design security architecture, implement guardrails, and audit compliance.',
    avgSalary: '£65,000 – £95,000',
    skills: ['AWS/Azure/GCP security', 'IAM & identity', 'Infrastructure-as-Code', 'Cloud compliance (CIS/SOC2)', 'Container security', 'Zero trust architecture'],
    missionSlugs: ['linux-hardening-fundamentals', 'docker-security-lab', 'cloud-security-audit-aws'],
    learningOrder: [
      'Linux & networking fundamentals',
      'AWS core services (EC2, S3, IAM, VPC)',
      'Terraform & Infrastructure-as-Code',
      'Cloud security best practices & CIS',
      'Container & Kubernetes security',
      'Cloud compliance frameworks',
    ],
  },
  {
    id: 'devsecops-engineer',
    title: 'DevSecOps Engineer',
    icon: '⚙️',
    description: 'Embed security into the software delivery lifecycle. Automate security testing, manage secrets, and build security as code.',
    avgSalary: '£70,000 – £110,000',
    skills: ['CI/CD pipelines', 'SAST/DAST', 'Container security', 'Secret management', 'IaC security', 'Python/Bash scripting'],
    missionSlugs: ['docker-security-lab', 'cloud-security-audit-aws', 'cicd-security-integration'],
    learningOrder: [
      'Git & version control',
      'Docker & containers',
      'CI/CD fundamentals (GitHub Actions)',
      'Security scanning tools (Semgrep, Trivy)',
      'IaC & Terraform',
      'Cloud platform security',
    ],
  },
];

export const roadmapCategories: RoadmapCategory[] = [
  {
    id: 'linux',
    title: 'Linux',
    icon: '🐧',
    color: '#fb923c',
    beginner: ['Command line basics', 'File permissions', 'Process management', 'Package management'],
    intermediate: ['Shell scripting', 'Systemd & services', 'Networking tools', 'Log management'],
    advanced: ['Kernel hardening', 'Audit framework', 'SELinux/AppArmor', 'Performance tuning'],
  },
  {
    id: 'scripting',
    title: 'Scripting',
    icon: '🐍',
    color: '#38bdf8',
    beginner: ['Python basics', 'Bash scripts', 'File I/O', 'HTTP requests'],
    intermediate: ['API integration', 'Log parsing', 'Automation scripts', 'Error handling'],
    advanced: ['Async Python', 'Custom tools', 'Threat automation', 'ML for security'],
  },
  {
    id: 'cloud',
    title: 'Cloud',
    icon: '☁️',
    color: '#a78bfa',
    beginner: ['AWS core services', 'IAM basics', 'VPC concepts', 'S3 & storage'],
    intermediate: ['Security groups', 'CloudTrail', 'GuardDuty', 'Config rules'],
    advanced: ['Zero trust arch', 'Cross-account', 'CSPM tools', 'Cloud forensics'],
  },
  {
    id: 'devops',
    title: 'DevOps',
    icon: '⚙️',
    color: '#00d4aa',
    beginner: ['Git & GitHub', 'Docker basics', 'CI/CD concepts', 'YAML syntax'],
    intermediate: ['Terraform', 'GitHub Actions', 'Container scanning', 'Secret mgmt'],
    advanced: ['Kubernetes security', 'Service mesh', 'GitOps', 'Platform engineering'],
  },
  {
    id: 'security',
    title: 'Security',
    icon: '🛡️',
    color: '#f87171',
    beginner: ['CIA triad', 'Common vulnerabilities', 'Network security', 'Cryptography basics'],
    intermediate: ['Threat modelling', 'OWASP Top 10', 'Pen testing basics', 'SIEM basics'],
    advanced: ['Threat hunting', 'Red team tactics', 'Malware analysis', 'Forensics'],
  },
  {
    id: 'ai',
    title: 'AI in Security',
    icon: '🤖',
    color: '#fb923c',
    beginner: ['AI/ML concepts', 'Anomaly detection basics', 'LLMs & security', 'Data pipelines'],
    intermediate: ['ML threat detection', 'NLP for logs', 'AI-assisted SIEM', 'LLM security'],
    advanced: ['Custom ML models', 'Adversarial ML', 'AI red teaming', 'Automated response'],
  },
];
