import type { Mission, CareerPath, RoadmapCategory } from './types';

export const missions: Mission[] = [
  {
    slug: 'linux-hardening-fundamentals',
    title: 'Linux Hardening Fundamentals',
    description: 'Secure a fresh Ubuntu server from scratch — configure SSH, set up firewalls, manage users, and eliminate attack surface.',
    tools: ['Linux', 'Bash', 'UFW', 'SSH', 'auditd'],
    difficulty: 'Beginner',
    duration: '4–6 hours',
    category: 'System Security',
    overview: `In this mission you'll take a freshly provisioned Ubuntu 22.04 server and harden it against common attack vectors. You'll disable unnecessary services, configure secure SSH access with key-based authentication, set up a stateful firewall with UFW, enforce strong password policies, and enable audit logging. By the end you'll have a repeatable hardening checklist you can apply to any Linux system.`,
    prerequisites: [
      'A Linux VM or cloud VPS (Ubuntu 22.04 recommended)',
      'SSH access with sudo privileges',
      'Basic command line familiarity (ls, cd, nano/vim)',
      'A terminal on your local machine',
    ],
    setup: `**Option 1 — Local VM (free):** Download [VirtualBox](https://www.virtualbox.org/) and the [Ubuntu 22.04 Server ISO](https://ubuntu.com/download/server). Create a new VM with 2GB RAM and 20GB disk, then install Ubuntu.\n\n**Option 2 — Cloud VPS (easiest):** Spin up a free-tier EC2 instance on AWS (t2.micro, Ubuntu 22.04) or a $4/month DigitalOcean Droplet. You'll get SSH access immediately.\n\nOnce you have access, SSH in and run \`sudo apt update && sudo apt upgrade -y\` before starting.`,
    tasks: [
      {
        id: 't1',
        title: 'Initial System Audit',
        description: 'Run a baseline security audit using lynis. Document open ports, running services, and current user accounts.',
        hint: 'Install lynis with `sudo apt install lynis`, then run `sudo lynis audit system`. Look at the "Suggestions" section — these are your starting points.',
        resources: [
          { label: 'Lynis documentation', url: 'https://cisofy.com/documentation/lynis/' },
          { label: 'ss command reference (open ports)', url: 'https://www.man7.org/linux/man-pages/man8/ss.8.html' },
        ],
      },
      {
        id: 't2',
        title: 'SSH Hardening',
        description: 'Disable root login, enforce key-based authentication only, change the default port, and configure fail2ban to block brute-force attempts.',
        hint: 'Edit `/etc/ssh/sshd_config` — set `PermitRootLogin no`, `PasswordAuthentication no`, and `Port 2222`. Run `sudo systemctl restart sshd` after each change. Always keep a second terminal open so you don\'t lock yourself out!',
        resources: [
          { label: 'OpenSSH server configuration', url: 'https://www.openssh.com/manual.html' },
          { label: 'fail2ban quickstart', url: 'https://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_with_SSH' },
          { label: 'SSH key generation guide', url: 'https://www.ssh.com/academy/ssh/keygen' },
        ],
      },
      {
        id: 't3',
        title: 'Firewall Configuration',
        description: 'Install and configure UFW. Define an allow-list of required ports (SSH, HTTP, HTTPS) and deny everything else by default.',
        hint: 'Run `sudo ufw default deny incoming && sudo ufw default allow outgoing`. Then `sudo ufw allow 2222/tcp` (your new SSH port). Enable with `sudo ufw enable`. Check status with `sudo ufw status verbose`.',
        resources: [
          { label: 'UFW essentials guide', url: 'https://help.ubuntu.com/community/UFW' },
          { label: 'Ubuntu firewall documentation', url: 'https://ubuntu.com/server/docs/firewalls' },
        ],
      },
      {
        id: 't4',
        title: 'User & Permission Management',
        description: 'Create a non-root admin user, configure sudo access with least privilege, and audit file permissions on sensitive directories.',
        hint: 'Use `sudo adduser secadmin` to create a new user, then `sudo usermod -aG sudo secadmin`. Check permissions on sensitive files with `ls -la /etc/passwd /etc/shadow /etc/sudoers`. Look for world-writable files with `find / -perm -o+w -type f 2>/dev/null`.',
        resources: [
          { label: 'Linux user management', url: 'https://ubuntu.com/server/docs/user-management' },
          { label: 'sudoers file reference', url: 'https://www.sudo.ws/docs/man/sudoers.man/' },
        ],
      },
      {
        id: 't5',
        title: 'Audit Logging with auditd',
        description: 'Configure auditd to track privilege escalation, file access on /etc, and login events. Export logs to a centralised location.',
        hint: 'Install with `sudo apt install auditd`. Add rules to `/etc/audit/rules.d/hardening.rules` — e.g. `-w /etc/passwd -p wa -k passwd_changes`. Restart with `sudo systemctl restart auditd` and check logs with `sudo ausearch -k passwd_changes`.',
        resources: [
          { label: 'auditd documentation', url: 'https://linux.die.net/man/8/auditd' },
          { label: 'Linux audit framework guide', url: 'https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-system_auditing' },
        ],
      },
    ],
    skills: ['Linux administration', 'Firewall configuration', 'SSH security', 'Audit logging', 'Least-privilege principles'],
    jobRelevance: 'Linux hardening is a foundational skill for SOC analysts, cloud security engineers, and DevSecOps engineers. Most cloud workloads run on Linux — knowing how to secure them is non-negotiable.',
  },
  {
    slug: 'docker-security-lab',
    title: 'Docker Security Lab',
    description: 'Scan container images for CVEs, build minimal secure images, and enforce runtime security policies across a multi-container stack.',
    tools: ['Docker', 'Trivy', 'Docker Compose', 'Linux', 'Falco'],
    difficulty: 'Intermediate',
    duration: '6–8 hours',
    category: 'Container Security',
    overview: `Containers are everywhere in modern infrastructure — and misconfigured containers are one of the top attack vectors. In this mission you'll learn to scan images for known vulnerabilities, build hardened Docker images using multi-stage builds and minimal base images, configure container runtime security with resource limits and read-only filesystems, and detect suspicious runtime behaviour with Falco.`,
    prerequisites: [
      'Docker and Docker Compose installed',
      'Basic Docker knowledge (pull, run, build)',
      'Linux system (Ubuntu/Debian recommended)',
      'At least 4GB of free RAM',
    ],
    setup: `Install Docker: \`curl -fsSL https://get.docker.com | sh\` then \`sudo usermod -aG docker $USER\` and log out/in.\n\nInstall Trivy: \`sudo apt install wget && wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.deb && sudo dpkg -i trivy_Linux-64bit.deb\`\n\nVerify with \`docker --version && trivy --version\`.`,
    tasks: [
      {
        id: 't1',
        title: 'Image Vulnerability Scanning',
        description: 'Use Trivy to scan a set of provided Docker images. Identify critical and high CVEs, document them, and propose remediation strategies.',
        hint: 'Run `trivy image nginx:1.21` to scan an older nginx image. Use `--severity HIGH,CRITICAL` to filter. Try `trivy image python:3.9` vs `python:3.9-slim` to see the difference a minimal base image makes.',
        resources: [
          { label: 'Trivy documentation', url: 'https://trivy.dev/latest/docs/' },
          { label: 'CVE database (NVD)', url: 'https://nvd.nist.gov/vuln/search' },
        ],
      },
      {
        id: 't2',
        title: 'Build a Hardened Image',
        description: 'Rewrite a provided Dockerfile using a distroless base image, multi-stage build, non-root user, and read-only filesystem.',
        hint: 'Start your final stage with `FROM gcr.io/distroless/base-debian12`. Add a non-root user with `RUN addgroup --system app && adduser --system --ingroup app app` and set `USER app`. Multi-stage: use `FROM node:18 AS builder` to build, then copy only the output into the distroless image.',
        resources: [
          { label: 'Google Distroless images', url: 'https://github.com/GoogleContainerTools/distroless' },
          { label: 'Docker multi-stage builds', url: 'https://docs.docker.com/build/building/multi-stage/' },
          { label: 'Dockerfile best practices', url: 'https://docs.docker.com/develop/develop-images/dockerfile_best-practices/' },
        ],
      },
      {
        id: 't3',
        title: 'Runtime Security Policies',
        description: 'Configure Docker Compose with security options: drop Linux capabilities, set memory/CPU limits, mount filesystems read-only, and disable privilege escalation.',
        hint: 'In your docker-compose.yml add: `security_opt: [no-new-privileges:true]`, `cap_drop: [ALL]`, `cap_add: [NET_BIND_SERVICE]`, `read_only: true`, and `mem_limit: 256m`. Use `tmpfs` for directories that need write access.',
        resources: [
          { label: 'Docker Compose security options', url: 'https://docs.docker.com/compose/compose-file/05-services/#security_opt' },
          { label: 'Linux capabilities reference', url: 'https://man7.org/linux/man-pages/man7/capabilities.7.html' },
        ],
      },
      {
        id: 't4',
        title: 'Network Segmentation',
        description: 'Define custom Docker networks to isolate containers. Verify that only intended services can communicate with each other.',
        hint: 'Define named networks in docker-compose.yml: `networks: frontend: backend:`. Assign each service to only the networks it needs. Test isolation with `docker exec <container> ping <other-container>` — it should fail across isolated networks.',
        resources: [
          { label: 'Docker networking overview', url: 'https://docs.docker.com/network/' },
          { label: 'Docker Compose networks', url: 'https://docs.docker.com/compose/networking/' },
        ],
      },
      {
        id: 't5',
        title: 'Runtime Threat Detection with Falco',
        description: 'Install Falco and write custom rules to detect shell spawning inside containers, unexpected file writes, and privilege escalation attempts.',
        hint: 'Install Falco with `curl -fsSL https://falco.org/repo/falcosecurity-packages.asc | sudo gpg --dearmor -o /usr/share/keyrings/falco-archive-keyring.gpg`. A custom rule looks like: `- rule: Shell in Container, desc: ..., condition: spawned_process and container and proc.name = bash, output: ..., priority: WARNING`.',
        resources: [
          { label: 'Falco getting started', url: 'https://falco.org/docs/getting-started/' },
          { label: 'Falco rules reference', url: 'https://falco.org/docs/rules/' },
        ],
      },
    ],
    skills: ['Container security', 'Vulnerability scanning', 'Image hardening', 'Runtime threat detection', 'Network segmentation'],
    jobRelevance: 'Container security expertise is in high demand. Cloud Security Engineers and DevSecOps roles at every major company require hands-on Docker and Kubernetes security skills.',
  },
  {
    slug: 'cloud-security-audit-aws',
    title: 'Cloud Security Audit with AWS',
    description: 'Audit a misconfigured AWS environment — find exposed S3 buckets, overly permissive IAM roles, open security groups, and missing CloudTrail.',
    tools: ['AWS', 'Terraform', 'Python', 'AWS CLI', 'Prowler'],
    difficulty: 'Intermediate',
    duration: '8–10 hours',
    category: 'Cloud Security',
    overview: `Cloud misconfigurations account for the majority of data breaches. In this mission you'll audit a deliberately misconfigured AWS environment using both manual techniques and automated tools like Prowler. You'll identify and remediate: public S3 buckets, wildcard IAM policies, overly permissive VPC security groups, disabled CloudTrail, and unencrypted EBS volumes. Finally, you'll codify the correct configuration using Terraform.`,
    prerequisites: [
      'An AWS account (free tier is sufficient)',
      'AWS CLI installed and configured',
      'Python 3.9+ installed',
      'Terraform installed',
      'Basic understanding of AWS services (EC2, S3, IAM)',
    ],
    setup: `**AWS CLI:** Install with \`pip install awscli\` then run \`aws configure\` and enter your Access Key ID and Secret Access Key from the AWS IAM console.\n\n**Terraform:** Download from [terraform.io/downloads](https://developer.hashicorp.com/terraform/downloads) and add to your PATH.\n\n**Prowler:** Install with \`pip install prowler\`. Verify with \`prowler --version\`.\n\nCreate a dedicated IAM user for this mission with read-only access (SecurityAudit managed policy) so you're not using your root account.`,
    tasks: [
      {
        id: 't1',
        title: 'Automated Audit with Prowler',
        description: 'Run Prowler against the target AWS account. Review the CIS benchmark findings and prioritise critical risks.',
        hint: 'Run `prowler aws --compliance cis_aws_foundations_benchmark_v1.4`. Prowler outputs findings by severity. Focus on CRITICAL and HIGH first. Use `prowler aws -s s3 iam` to scope to specific services.',
        resources: [
          { label: 'Prowler documentation', url: 'https://docs.prowler.com/' },
          { label: 'CIS AWS Foundations Benchmark', url: 'https://www.cisecurity.org/benchmark/amazon_web_services' },
        ],
      },
      {
        id: 't2',
        title: 'S3 Bucket Security',
        description: 'Identify publicly accessible S3 buckets. Review bucket policies and ACLs, enable Block Public Access, and implement server-side encryption.',
        hint: 'Use `aws s3api list-buckets` to list all buckets. Check each with `aws s3api get-bucket-acl --bucket <name>` and `aws s3api get-bucket-policy --bucket <name>`. Enable block public access with `aws s3api put-public-access-block --bucket <name> --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true`.',
        resources: [
          { label: 'S3 Block Public Access', url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html' },
          { label: 'S3 security best practices', url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html' },
        ],
      },
      {
        id: 't3',
        title: 'IAM Policy Remediation',
        description: 'Identify IAM users/roles with wildcard permissions. Apply least-privilege principles and replace overly broad policies with scoped ones.',
        hint: 'Use the AWS IAM Access Analyzer or `aws iam get-account-authorization-details` to export all policies. Look for `"Action": "*"` or `"Resource": "*"`. Use the IAM Policy Simulator to test what a policy actually allows.',
        resources: [
          { label: 'IAM Access Analyzer', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html' },
          { label: 'IAM best practices', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html' },
          { label: 'IAM Policy Simulator', url: 'https://policysim.aws.amazon.com/' },
        ],
      },
      {
        id: 't4',
        title: 'VPC & Security Group Hardening',
        description: 'Find security groups with 0.0.0.0/0 ingress rules on sensitive ports. Tighten rules and document the required access matrix.',
        hint: 'Run `aws ec2 describe-security-groups --query "SecurityGroups[?IpPermissions[?IpRanges[?CidrIp==\'0.0.0.0/0\']]]"` to find all security groups with open ingress. Pay particular attention to ports 22 (SSH), 3389 (RDP), 3306 (MySQL), and 5432 (PostgreSQL).',
        resources: [
          { label: 'VPC security groups guide', url: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html' },
          { label: 'AWS security group best practices', url: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-best-practices.html' },
        ],
      },
      {
        id: 't5',
        title: 'Terraform Remediation',
        description: 'Codify all security fixes as Terraform resources. Run terraform plan/apply and verify the changes using the AWS CLI.',
        hint: 'Write a `main.tf` that defines your secure S3 bucket, IAM policies, and security group rules. Run `terraform init && terraform plan` to preview changes. Use `terraform apply` to apply. The AWS provider docs have examples for every resource type.',
        resources: [
          { label: 'Terraform AWS Provider docs', url: 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs' },
          { label: 'Terraform getting started', url: 'https://developer.hashicorp.com/terraform/tutorials/aws-get-started' },
        ],
      },
    ],
    skills: ['AWS security', 'IAM policies', 'Cloud compliance (CIS)', 'Terraform', 'Incident response'],
    jobRelevance: 'Cloud Security Engineers and DevSecOps roles require deep AWS knowledge. Cloud misconfiguration skills are tested in interviews and used daily on the job.',
  },
  {
    slug: 'automated-threat-detection-pipeline',
    title: 'Automated Threat Detection Pipeline',
    description: 'Build a SIEM-style detection pipeline using Python and the ELK stack to ingest logs, detect anomalies, and trigger automated alerts.',
    tools: ['Python', 'Elasticsearch', 'Logstash', 'Kibana', 'Suricata', 'Sigma'],
    difficulty: 'Advanced',
    duration: '10–14 hours',
    category: 'Threat Detection',
    overview: `SOC analysts spend most of their time investigating alerts — but the pipeline that generates those alerts is often opaque. In this mission you'll build a full threat detection pipeline from scratch: ingest web server logs and network traffic using Logstash, write detection rules using Sigma, correlate events in Elasticsearch, visualise them in Kibana, and write Python automation to enrich and escalate high-severity events.`,
    prerequisites: [
      'Docker and Docker Compose installed',
      'At least 8GB RAM (ELK is memory-hungry)',
      'Python 3.10+ with pip',
      'Basic understanding of log formats (JSON, syslog)',
      'Familiarity with Linux command line',
    ],
    setup: `**System requirement:** Run \`free -h\` to confirm you have 8GB+ RAM available. If not, use a cloud VM (t3.large on AWS, or a $12/mo DigitalOcean droplet).\n\n**Set vm.max_map_count:** Elasticsearch requires \`sudo sysctl -w vm.max_map_count=262144\` (add to \`/etc/sysctl.conf\` to persist).\n\n**Clone the starter repo:** \`git clone https://github.com/elastic/docker-elk && cd docker-elk && docker-compose up -d\`. Kibana will be available at http://localhost:5601 (default creds: elastic / changeme).`,
    tasks: [
      {
        id: 't1',
        title: 'ELK Stack Setup',
        description: 'Deploy Elasticsearch, Logstash, and Kibana using Docker Compose. Configure TLS and authentication between components.',
        hint: 'Use the elastic/docker-elk repo as a starting point. Change the default password immediately in the `.env` file. Enable xpack.security by setting `xpack.security.enabled=true` in the elasticsearch config. Access Kibana at http://localhost:5601.',
        resources: [
          { label: 'elastic/docker-elk on GitHub', url: 'https://github.com/deviantony/docker-elk' },
          { label: 'Elasticsearch security guide', url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-cluster.html' },
        ],
      },
      {
        id: 't2',
        title: 'Log Ingestion Pipeline',
        description: 'Write Logstash pipelines to ingest Apache/Nginx access logs and Suricata alerts. Parse, normalise, and enrich events with GeoIP data.',
        hint: 'A Logstash pipeline has three sections: input (file, beats), filter (grok, date, geoip), and output (elasticsearch). Use the grok pattern `COMBINEDAPACHELOG` for Apache logs. Add `geoip { source => "clientip" }` to enrich with location data.',
        resources: [
          { label: 'Logstash pipeline configuration', url: 'https://www.elastic.co/guide/en/logstash/current/configuration.html' },
          { label: 'Grok pattern reference', url: 'https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html' },
          { label: 'Elastic Common Schema (ECS)', url: 'https://www.elastic.co/guide/en/ecs/current/ecs-reference.html' },
        ],
      },
      {
        id: 't3',
        title: 'Sigma Detection Rules',
        description: 'Convert three real-world Sigma rules (brute-force, port scan, data exfiltration) into Elasticsearch queries. Test against sample log data.',
        hint: 'Install sigma-cli with `pip install sigma-cli`. Convert a rule with `sigma convert -t lucene -p elasticsearch my-rule.yml`. The Sigma community rules repo has hundreds of pre-built rules at github.com/SigmaHQ/sigma.',
        resources: [
          { label: 'Sigma rules repository', url: 'https://github.com/SigmaHQ/sigma' },
          { label: 'sigma-cli documentation', url: 'https://github.com/SigmaHQ/sigma-cli' },
          { label: 'Elasticsearch Query DSL', url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html' },
        ],
      },
      {
        id: 't4',
        title: 'Kibana Dashboards',
        description: 'Build a SOC dashboard showing: top source IPs, alert severity timeline, geo-map of sources, and anomaly trends.',
        hint: 'In Kibana, go to Dashboard → Create new. Use a Data Table for top IPs, a Bar chart for timeline, a Map visualisation for geo data. Save your index pattern first under Stack Management → Index Patterns.',
        resources: [
          { label: 'Kibana dashboard guide', url: 'https://www.elastic.co/guide/en/kibana/current/dashboard.html' },
          { label: 'Kibana maps documentation', url: 'https://www.elastic.co/guide/en/kibana/current/maps.html' },
        ],
      },
      {
        id: 't5',
        title: 'Python Alert Automation',
        description: 'Write a Python script that polls Elasticsearch for new high-severity alerts, enriches them via VirusTotal, and sends formatted notifications via webhook.',
        hint: 'Use the `elasticsearch-py` client: `pip install elasticsearch`. Query with `es.search(index="alerts-*", body={"query": {"term": {"severity": "high"}}})`. For VirusTotal enrichment, use the free API (500 requests/day) with `pip install vt-py`.',
        resources: [
          { label: 'elasticsearch-py client docs', url: 'https://elasticsearch-py.readthedocs.io/' },
          { label: 'VirusTotal API v3', url: 'https://developers.virustotal.com/reference/overview' },
        ],
      },
    ],
    skills: ['SIEM operations', 'ELK Stack', 'Sigma rules', 'Python scripting', 'Log analysis', 'Threat detection'],
    jobRelevance: 'SOC Analysts and Security Engineers who can build and tune detection pipelines command premium salaries. SIEM expertise is listed in virtually every senior security role.',
  },
  {
    slug: 'cicd-security-integration',
    title: 'CI/CD Security Integration',
    description: 'Embed security scanning into a GitHub Actions pipeline — SAST, dependency scanning, secret detection, container scanning, and IaC validation.',
    tools: ['GitHub Actions', 'Docker', 'Terraform', 'Semgrep', 'Trivy', 'tfsec', 'Gitleaks'],
    difficulty: 'Advanced',
    duration: '8–12 hours',
    category: 'DevSecOps',
    overview: `Security is most effective when it's automated and shift-left. In this mission you'll take an existing CI/CD pipeline and transform it into a security-first workflow. You'll add static analysis with Semgrep, dependency vulnerability scanning, secret detection with Gitleaks, container image scanning with Trivy, and Infrastructure-as-Code security validation with tfsec — all gated to block insecure deployments.`,
    prerequisites: [
      'A GitHub account with a repository to work with',
      'Basic Git knowledge (commit, push, pull request)',
      'Docker installed locally',
      'Basic understanding of CI/CD concepts',
      'A simple app to work with (Node.js or Python recommended)',
    ],
    setup: `**Fork a starter repo:** Fork [github.com/juice-shop/juice-shop](https://github.com/juice-shop/juice-shop) — this is a deliberately vulnerable Node.js app perfect for practising security scanning.\n\n**Enable GitHub Actions:** In your fork, go to Actions tab and click "I understand my workflows, go ahead and enable them".\n\n**Create a workflow file:** Create \`.github/workflows/security.yml\` — this is where all your security tools will live. The YAML indentation must be exact.`,
    tasks: [
      {
        id: 't1',
        title: 'Secret Detection with Gitleaks',
        description: "Integrate Gitleaks into the pipeline. Intentionally commit a fake secret, verify it's caught, then configure allowlist rules for false positives.",
        hint: 'Add this to your workflow: `- uses: gitleaks/gitleaks-action@v2`. Create a `.gitleaks.toml` config file to allowlist known false positives. Test by committing a fake AWS key like `AKIAIOSFODNN7EXAMPLE` — Gitleaks should catch it.',
        resources: [
          { label: 'Gitleaks GitHub Action', url: 'https://github.com/gitleaks/gitleaks-action' },
          { label: 'Gitleaks configuration', url: 'https://github.com/gitleaks/gitleaks#configuration' },
        ],
      },
      {
        id: 't2',
        title: 'Static Application Security Testing',
        description: 'Add Semgrep to scan Python/JavaScript code for injection vulnerabilities, hardcoded credentials, and insecure dependencies.',
        hint: 'Add `- uses: returntocorp/semgrep-action@v1` with `config: auto` to use Semgrep\'s recommended rules. Or use `config: p/owasp-top-ten` to focus on OWASP issues. Semgrep will comment on PRs automatically.',
        resources: [
          { label: 'Semgrep GitHub Action', url: 'https://github.com/returntocorp/semgrep-action' },
          { label: 'Semgrep rule registry', url: 'https://semgrep.dev/r' },
          { label: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/' },
        ],
      },
      {
        id: 't3',
        title: 'Container Image Scanning',
        description: 'Integrate Trivy to scan the application Docker image on every PR. Configure severity thresholds and block merges on CRITICAL findings.',
        hint: 'Use `- uses: aquasecurity/trivy-action@master` with `image-ref: your-image:latest`, `severity: CRITICAL,HIGH`, and `exit-code: 1` to fail the build. Build the image first with `docker build -t your-image:latest .`.',
        resources: [
          { label: 'Trivy GitHub Action', url: 'https://github.com/aquasecurity/trivy-action' },
          { label: 'Trivy configuration options', url: 'https://trivy.dev/latest/docs/configuration/' },
        ],
      },
      {
        id: 't4',
        title: 'IaC Security Scanning',
        description: 'Add tfsec and Checkov to validate Terraform code. Identify and fix three deliberately insecure Terraform resources.',
        hint: 'Add `- uses: aquasecurity/tfsec-action@v1.0.0` pointing at your Terraform directory. Then add `- uses: bridgecrewio/checkov-action@master`. Create intentionally insecure resources (e.g. an S3 bucket with `acl = "public-read"`) to see them caught.',
        resources: [
          { label: 'tfsec GitHub Action', url: 'https://github.com/aquasecurity/tfsec-action' },
          { label: 'Checkov documentation', url: 'https://www.checkov.io/1.Welcome/Quick%20Start.html' },
          { label: 'tfsec checks reference', url: 'https://aquasecurity.github.io/tfsec/latest/checks/aws/' },
        ],
      },
      {
        id: 't5',
        title: 'Security Gates & Reporting',
        description: 'Implement a consolidated security report as a PR comment. Configure branch protection rules so all security gates must pass before merge.',
        hint: 'Use the `peter-evans/create-or-update-comment` action to post a summary comment on PRs. Go to Settings → Branches → Add rule, enable "Require status checks to pass before merging" and add your security job names as required checks.',
        resources: [
          { label: 'GitHub branch protection rules', url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches' },
          { label: 'GitHub Actions security hardening', url: 'https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions' },
        ],
      },
    ],
    skills: ['DevSecOps', 'GitHub Actions', 'SAST', 'Container security', 'IaC security', 'Shift-left security'],
    jobRelevance: 'DevSecOps is the fastest-growing security discipline. Companies that have adopted DevOps need security engineers who can speak the same language as developers and automate security into pipelines.',
  },
];

export const careerPaths: CareerPath[] = [
  {
    id: 'soc-analyst',
    title: 'SOC Analyst',
    icon: '🔍',
    description: 'Monitor, detect, and respond to security threats in real time. The entry point for many cybersecurity careers — high demand, clear progression.',
    avgSalary: '£35,000 – £55,000',
    skills: ['SIEM (Splunk/ELK)', 'Incident response', 'Log analysis', 'Threat intelligence', 'Network monitoring', 'Sigma/YARA rules'],
    missionSlugs: ['linux-hardening-fundamentals', 'automated-threat-detection-pipeline'],
    learningOrder: [
      'Linux fundamentals & command line',
      'Networking basics (TCP/IP, DNS, HTTP)',
      'SIEM concepts and log analysis',
      'Threat detection & Sigma rules',
      'Incident response procedures',
      'Threat intelligence feeds',
    ],
  },
  {
    id: 'cloud-security-engineer',
    title: 'Cloud Security Engineer',
    icon: '☁️',
    description: 'Secure cloud infrastructure across AWS, Azure, or GCP. Design security architecture, implement guardrails, and audit compliance.',
    avgSalary: '£65,000 – £95,000',
    skills: ['AWS/Azure/GCP security', 'IAM & identity', 'Infrastructure-as-Code', 'Cloud compliance (CIS/SOC2)', 'Container security', 'Zero trust architecture'],
    missionSlugs: ['linux-hardening-fundamentals', 'docker-security-lab', 'cloud-security-audit-aws'],
    learningOrder: [
      'Linux & networking fundamentals',
      'AWS core services (EC2, S3, IAM, VPC)',
      'Terraform & Infrastructure-as-Code',
      'Cloud security best practices & CIS',
      'Container & Kubernetes security',
      'Cloud compliance frameworks',
    ],
  },
  {
    id: 'devsecops-engineer',
    title: 'DevSecOps Engineer',
    icon: '⚙️',
    description: 'Embed security into the software delivery lifecycle. Automate security testing, manage secrets, and build security as code.',
    avgSalary: '£70,000 – £110,000',
    skills: ['CI/CD pipelines', 'SAST/DAST', 'Container security', 'Secret management', 'IaC security', 'Python/Bash scripting'],
    missionSlugs: ['docker-security-lab', 'cloud-security-audit-aws', 'cicd-security-integration'],
    learningOrder: [
      'Git & version control',
      'Docker & containers',
      'CI/CD fundamentals (GitHub Actions)',
      'Security scanning tools (Semgrep, Trivy)',
      'IaC & Terraform',
      'Cloud platform security',
    ],
  },
];

export const roadmapCategories: RoadmapCategory[] = [
  {
    id: 'linux',
    title: 'Linux',
    icon: '🐧',
    color: '#fb923c',
    beginner: ['Command line basics', 'File permissions', 'Process management', 'Package management'],
    intermediate: ['Shell scripting', 'Systemd & services', 'Networking tools', 'Log management'],
    advanced: ['Kernel hardening', 'Audit framework', 'SELinux/AppArmor', 'Performance tuning'],
  },
  {
    id: 'scripting',
    title: 'Scripting',
    icon: '🐍',
    color: '#38bdf8',
    beginner: ['Python basics', 'Bash scripts', 'File I/O', 'HTTP requests'],
    intermediate: ['API integration', 'Log parsing', 'Automation scripts', 'Error handling'],
    advanced: ['Async Python', 'Custom tools', 'Threat automation', 'ML for security'],
  },
  {
    id: 'cloud',
    title: 'Cloud',
    icon: '☁️',
    color: '#a78bfa',
    beginner: ['AWS core services', 'IAM basics', 'VPC concepts', 'S3 & storage'],
    intermediate: ['Security groups', 'CloudTrail', 'GuardDuty', 'Config rules'],
    advanced: ['Zero trust arch', 'Cross-account', 'CSPM tools', 'Cloud forensics'],
  },
  {
    id: 'devops',
    title: 'DevOps',
    icon: '⚙️',
    color: '#00d4aa',
    beginner: ['Git & GitHub', 'Docker basics', 'CI/CD concepts', 'YAML syntax'],
    intermediate: ['Terraform', 'GitHub Actions', 'Container scanning', 'Secret mgmt'],
    advanced: ['Kubernetes security', 'Service mesh', 'GitOps', 'Platform engineering'],
  },
  {
    id: 'security',
    title: 'Security',
    icon: '🛡️',
    color: '#f87171',
    beginner: ['CIA triad', 'Common vulnerabilities', 'Network security', 'Cryptography basics'],
    intermediate: ['Threat modelling', 'OWASP Top 10', 'Pen testing basics', 'SIEM basics'],
    advanced: ['Threat hunting', 'Red team tactics', 'Malware analysis', 'Forensics'],
  },
  {
    id: 'ai',
    title: 'AI in Security',
    icon: '🤖',
    color: '#fb923c',
    beginner: ['AI/ML concepts', 'Anomaly detection basics', 'LLMs & security', 'Data pipelines'],
    intermediate: ['ML threat detection', 'NLP for logs', 'AI-assisted SIEM', 'LLM security'],
    advanced: ['Custom ML models', 'Adversarial ML', 'AI red teaming', 'Automated response'],
  },
];
